language: go
go: 1.8.3
install:
  - go get -u github.com/go-bindata/go-bindata/...

script: make build

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: pkg/*
  skip_cleanup: true
  on:
    tags: true
